language: node_js
node_js:
- '10'
branches: 
only:
- "/^feature.*$/"
after_success:
- bash .travis/deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_819282be80f9_key -iv $encrypted_819282be80f9_iv -in id_rsa.enc -out id_rsa -d
