language: node_js
node_js:
- '10'
branches: 
only:
- "/^feature.*$/"
before_install: 
- openssl aes-256-cbc -K $encrypted_819282be80f9_key -iv $encrypted_819282be80f9_iv -in id_rsa.enc -out id_rsa -d
addons:
        ssh_known_hosts: 116.202.28.78
after_success:
- bash deploy.sh
