language: node_js
node_js:
  - "10"
branches:
only:
  - /feature\/.*/
except:
        - master
before_install: 
        - openssl aes-256-cbc -K $encrypted_1505e8a72b1d_key -iv $encrypted_1505e8a72b1d_iv -in id_rsa.enc -out id_rsa -d
after_install:
        - bash deploy.sh
